### ISSUE TITLE
[1W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by seojeahyean** [MJU-Coin/22-S-React#161]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 상세 개발 내용

### 주요 개발 내용 2
- 피그마를 사용하여 초안 작성

![image](https://user-images.githubusercontent.com/102343946/182876344-4831039c-044f-4618-956a-37639991329a.png)

**Comment by MinsuKim21** [comment]
DB 수정할거임??

**Comment by SeoJeHyun** [comment]
DB요? 백엔드 말씀하시는건가?

**Comment by MinsuKim21** [comment]
ㅇㅇ

**Comment by MinsuKim21** [comment]
정렬을 뭐를 기준으로 할꺼냐고
