### ISSUE TITLE
[1W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by keemsebin** [MJU-Coin/22-S-React#165]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [x] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 상태 관리를 위한 useState를 구현하고 하위 컴포넌트에 값을 전달해주었습니다!

### 주요 개발 내용 2
- 아이템이 추가된 후 목록에서 조회가 가능하도록 구현했습니다! 디자인은 더 손 봐야 할 것 같습니다 ㅠㅠ

**Comment by dojinyou** [comment]
브랜치 전략 / commit convention 잘 지키면서 하고 있는 거지?
