### ISSUE TITLE
[1W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by xxxjinn** [MJU-Coin/22-S-React#173]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View -- 진행 중!
- [ ] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- list view를 기능을 제외한 형태만 구현해 놓았습니다.  (todoItem 파일, todoList 파일) css가 제 마음에 완벽하게 들지 않아서 자꾸 발목을 잡고 있습니다. 아직 기능이나 통신에 대해서는 손도 못 대고 있는데 역시 모든 공부는 기초가 탄탄해야 한다는 생각이 들어요.

**Comment by dojinyou** [comment]
👍 베리굿
