### ISSUE TITLE
[1W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by solmin12** [MJU-Coin/22-S-React#179]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 화면을 새로 수정하였습니다
![화면 캡처 2022-08-07 182919](https://user-images.githubusercontent.com/101556294/183284529-ab8b109b-b134-4a47-8584-2caf18e8e950.png)

### 화면 구성 Component생성
- TodoContainer,TodoItem Component를 생성하였습니다.

### Todo 아이템 추가
- addItem이라는 함수를 만들어 add버튼 클릭 이벤트가 발생 시 input창에 입력된 값이 TodoItem에 추가되어 보여지도록 하였습니다.

**Comment by k-kbk** [comment]
예시 사진 좀 더 올려주세요!

**Comment by solmin12** [comment]
![화면 캡처 2022-08-07 215201](https://user-images.githubusercontent.com/101556294/183292878-b8bdc509-81a5-4b80-b6ff-f8ab41ccf8f3.png)
현재는 여기까지 진행했습니다!
다음은 edit버튼과 del버튼이 작동하도록 만들 계획입니다

**Comment by k-kbk** [comment]
👍👍
