### ISSUE TITLE
[IW3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by 5uhwann** [MJU-Coin/22-S-React#181]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- TodoList아이템 전체조회 구현: 메인페이지 렌더링 시 useEffect()를 사용해 TodoList아이템 전체 조회

### 주요 개발 내용 2
-
