### ISSUE TITLE
[2W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by gahyuun** [MJU-Coin/22-S-React#185]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 상세 개발 내용
제출 버튼 누를 때마다 함수를 실행해서 데이터를 서버 todo정보에 추가하는 작업을 했습니다 
처음에 input 입력값이 바뀔때마다 데이터를 추가하는 작업을 하는 실수를 하구.... 반성했습니당
db툴을 깔아서 관리하려고요 !
얼른 다른 작업도 빨리 해봐야겠어용 

### 주요 개발 내용 2
- 상세 개발 내용

**Comment by dojinyou** [comment]
db툴은 어떤거?!! 클릭 빠르게 2번 하면 혹시 요청 2번 가나요?

**Comment by gahyuun** [comment]
db툴은 datagrip이나 mysqlworkbench 추천 받았습니당 !! 아직 깔진 않았지만 .. ㅎㅎㅎ 클릭 2번 지금 빠르게 해봤는데 요청 1번 가요!

**Comment by dojinyou** [comment]
> db툴은 datagrip이나 mysqlworkbench 추천 받았습니당 !! 아직 깔진 않았지만 .. ㅎㅎㅎ 클릭 2번 지금 빠르게 해봤는데 요청 1번 가요!

datagrip 추천! 나중에 IntelliJ 사용하게 되면 환경도 비슷하고 편해서 좋더라 ~ mysqlWorkbench는 약간 넘 소소하고 ㅋㅋ
