### ISSUE TITLE
[2W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by keemsebin** [MJU-Coin/22-S-React#186]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- checkbox만 해결하고 삭제기능 구현하려고 했는데 하나만 체크해도 전체가 체크되네요,, 발목잡혔습니다

**Comment by dojinyou** [comment]
오호~ 트러블 슛팅!! 성장하는 좋은 기회!! 화이팅!
