### ISSUE TITLE
[2W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by euntaek4187** [MJU-Coin/22-S-React#190]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현-- 진행 중!
- [X] 화면 레이아웃 구현 : List View-- 진행 중!
- [ ] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 데스크탑에서 작업 공간 따로 만들어서 컴포넌트 만들고 파일도 여러 개 건드려보며 실험하고 있습니다
- 혹시 작업중인 todo프로젝트 파일에서 하다가 오류 뜰까봐서요 ㅠㅠ
이제야 뭔가 감이 잡힌것... 같습니다 천천히 구글링 하고 유튜브에 다른 비슷한프로젝트 찾아보며 진행하면 될것같아요
컴포넌트 구현이랑 레이아웃 구현중입니다.

**Comment by dojinyou** [comment]
오호 여러 개 건드려보면서 실험해보는 거 좋은 공부 방법이지! 굿굿 잘하고 있네
