### ISSUE TITLE
[2W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by root-51** [MJU-Coin/22-S-React#191]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가 --진행 중!
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

###  아이템 추가 기능을 개발하기 위한 자료조사
-  공부중입니다.
### 화면 레이아웃 수정(디자인)
- 아이템의 내용을 적을 텍스트박스를 추가했습니다.
![image](https://user-images.githubusercontent.com/103632151/183820689-bdd41e37-0d47-4cbd-a73c-5cc800117b69.png)

**Comment by k-kbk** [comment]
예시 사진도 같이 올려주세요!

**Comment by k-kbk** [comment]
👍
