### ISSUE TITLE
[2W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by haejun1** [MJU-Coin/22-S-React#195]
## 📌 기능 구현 현황
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 폰트적용
- 구글폰트를 이용해 폰트를 적용 했습니다

### List 만들기
- List 수정 삭제 추가를 만들었습니다(진행중)

**Comment by MinsuKim21** [comment]
사진 첨부 있으면 좋을듯
