### ISSUE TITLE
[2W1D] 리액트 Todo 프로젝트 개발 현황 

### ISSUE THREAD

**Issue by yougyung** [MJU-Coin/22-S-React#196]
## 📌 기능 구현 현황
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 버튼을 누르면, input창이 생성되어 Todo를 추가할 수 있게 아이템 추가 목록 구현

### 주요 개발 내용 2
- 아이템 클릭 시, 해당 id의 Todo가 삭제되는 아이템 삭제 기능 구현

![image](https://user-images.githubusercontent.com/75975946/183679170-a9fbdf87-0f44-4c9b-98cb-224788ae547e.png)

**Comment by k-kbk** [comment]
👍👍
