### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by yougyung** [MJU-Coin/22-S-React#198]
## 📌 기능 구현 현황
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정 --진행중!
- [ ] 기능 구현 : Todo 아이템 상태 변경 --진행중!
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 아이템 수정과 상태 변경을 진행하고 있어요!

### 주요 개발 내용 2
- 여행 때문에 코드를 못 만져서 기능 구현의 변화가 없는데, 다녀와서 열심히 이어하겠습니다!

**Comment by k-kbk** [comment]
🤘
