### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by solmin12** [MJU-Coin/22-S-React#199]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가(진행중)
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제(진행중)
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 서버 연결
- 선배가 알려준 사이트 덕분에 거의 된 것 같지만 아직 원리를 이해하지 못했어요..

### 추가버튼과 삭제버튼 구현
- 변수 이름을 헷갈리게 설정해두어서 다시 명확하게 만들고 개발하는 중입니다.

**Comment by k-kbk** [comment]
👍👍
