### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by euntaek4187** [MJU-Coin/22-S-React#200]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현 -- 진행 중!
- [X] 화면 레이아웃 구현 : List View -- 진행 중!
- [X] 기능 구현 : Todo 아이템 추가 -- 진행 중!
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

## 👩‍💻 주요 개발 내용

-화면 컴포넌트, 레이아웃 천천히 추가하고 수정하고 있습니다 완벽한게 아니라서 진행중으로 표시했습니다..
기능 구현중 todo 아이템 추가하는거 진행중입니다.

너무 어려워요... 데이터를 도커로 관리하고.. axios? 이거 꼭 사용해야 하는건가요..?

**Comment by dojinyou** [comment]
- 통신 방식은 http를 이용! 그러면 js에서 기본 제공 되는 http 라이브러리인 fetch를 쓰거나 이걸로 더 편하게 만들어놓은 axios를 쓰거나?!
