### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by keemsebin** [MJU-Coin/22-S-React#201]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 아이템 추가하고 삭제하고 난 뒤 다시 아이템 추가할 때 자꾸 전에 삭제했던 아이템이 추가되는 오류가 생겨서 잡았습니다..! 아이템이 삭제가 되면 id값에도 변경이 있어야 하는데 변경이 없어서 생긴 오류였습니다.
### 주요 개발 내용 2
- 현재 아이템 수정 기능 구현 중인데 더블 클릭시 변경이 되도록 만들려고 하고있습니다 ! 지금까지 했던 기능 중에 수정이 가장 어려운 것 같아요.

**Comment by dojinyou** [comment]
디버깅 좋고! 더블 클릭은 더블 클릭 이벤트가 발생하면 해당 컴포넌트를 수정 가능한 컴포넌트로 교체하는 방식으로 하면 될 것 같은데??
