### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by xxxjinn** [MJU-Coin/22-S-React#202]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [X] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 백엔드는 일단 나중에 연결해보자 라는 생각으로 리액트 내에서 아이템 삭제와 추가 기능을 구현해 놓았습니다.

### 주요 개발 내용 2
- '생성 날짜에 따른 필터' 를 정확히 어떻게 구현 해야 할 지 모르겠어서 오늘의 날짜를 하단에 띄웠습니다.

**Comment by dojinyou** [comment]
일단 나중에 연결해보자도 나쁘지 않지! 인메모리 db를 연결할 때도 추상화를 통해서 추후에 구현체가 변경될 떄 임팩트를 최소화 하는 게 좋을 거 같네용!!
