### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by gahyuun** [MJU-Coin/22-S-React#203]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 상세 개발 내용
- 
전체 목록을 조회하는 거에서 무한 렌더링이 일어나거나 새로고침해야만 뜨는 오류가 발생했고 그 오류를 해결했는데 정작 그 문제의 정확한 원인을 잘 모르겠어요 .. 좀 더 찾아봐야겠어요

### 주요 개발 내용 2
- 상세 개발 내용
번거롭지만 개발할때마다 중요한 부분은 좀 기록하려고 하고 있어요

**Comment by dojinyou** [comment]
디버깅을 잘하기 위해서는 브레이크 걸고 콘솔 말고 디버깅 기능을 직접 이용해 보는 것도 좋지!

기록하는 습관 ㅠㅠ 나도 기록 해야되는데
