### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by root-51** [MJU-Coin/22-S-React#205]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가 --진행 중!
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

## 👩‍💻 주요 개발 내용

![image](https://user-images.githubusercontent.com/103632151/184150388-90ea6038-e6ea-4424-af53-8a02179f26b3.png)

### 컴포넌트 추출
- 코드가 깔끔하지 않은 것같아 컴포넌트를 추출했습니다.

### 리팩토링
- 컴포넌트를 추출하면서 클래스명과 css 구조를 변경했습니다. 특히 css는 정말 신경 많이 써서 언제든 쉽게 읽고 수정가능하게끔..했습니다.

**Comment by k-kbk** [comment]
👍
