### ISSUE TITLE
[2W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by 5uhwann** [MJU-Coin/22-S-React#209]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [X] 화면 필터 : 완료 여부에 따른 필터
- [X] 화면 필터 : 생성 날짜에 따른 필터
- [X] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 생성일에 따른 필터 구현
- Grid View 구현
### 주요 개발 내용 2
완성화면
<img width="1726" alt="스크린샷 2022-08-12 01 23 18" src="https://user-images.githubusercontent.com/106325839/184182275-c3cfc685-f3f0-48e6-8ea6-529e6d8ffb15.png">
<img width="1723" alt="스크린샷 2022-08-12 01 23 29" src="https://user-images.githubusercontent.com/106325839/184182290-3fcbe67f-4666-4fac-a740-d066a725a032.png">
<img width="1722" alt="스크린샷 2022-08-12 01 23 37" src="https://user-images.githubusercontent.com/106325839/184182301-5c8cbecd-0893-421c-bf18-f0dea86f787b.png">
<img width="1724" alt="스크린샷 2022-08-12 01 24 40" src="https://user-images.githubusercontent.com/106325839/184182317-5c9d6ef5-991d-41c2-93dd-8aa0e6fc037b.png">

**Comment by dojinyou** [comment]
올ㅋ
