### ISSUE TITLE
[2W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by xxxjinn** [MJU-Coin/22-S-React#210]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 기능 요구에는 없지만.. 허전하다는 생각이 들어서 남은 todo의 개수를 보여주는 기능을 만들었습니다.
- 백엔드는 살짝 막막해서 일단 먼저 혼자 더 공부를 많이 해보고 궁금한 점이 있다면 꼭 물어보겠습니다!

### 주요 개발 내용 2
- 예전에 신경쓰였던 css를 어떻게 고치긴 고쳤습니다.
- (todo item에 마우스를 올리면 x 표시랑 todo item이 왼쪽으로 움직이는(?) 이슈였습니다)
- 사소한 것이었지만 어쨌든 해결했다는 것에 작은 성취와 기쁨...

**Comment by dojinyou** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋcss도 하나 보면 한 없지..... 삭제하면 약간 아래쪽으로 멀어지면서 fade out 처럼 희미하게 사라지는 효과를 넣는 다던지... 추가 하면 작성한 위치에서 튀어 나와서 쭉 내려가서 위치하게 만든다던지...ㅋㅋㅋ
