### ISSUE TITLE
[2W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by keemsebin** [MJU-Coin/22-S-React#211]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [X] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 수정하는 기능을 추가했습니다 ! 추가적으로 글씨체나, listview가 너무 작아보여서 디자인 쪽으로 많이 다듬었습니다! 하지만 마음에 들지는 않아요 

![화면 캡처 2022-08-13 120530](https://user-images.githubusercontent.com/108217858/184466284-a6d63325-ec20-4ab2-8e16-1830bcbbc109.png)

**Comment by dojinyou** [comment]
오호 깔끔한데... !! 굿굿 ~~~
