### ISSUE TITLE
[2W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by euntaek4187** [MJU-Coin/22-S-React#213]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회 -- 진행 중!
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
-화면 컴포넌트, 레이아웃 작업 끝
-todo아이템 추가 기능 구현 끝

문제발생: 체크박스 클릭시 todo아이템 전체가 체크됨 --해결중

**Comment by dojinyou** [comment]
todo 아이템의 체크 동작 원리와 예상 문제 원인 알려주세요!
