### ISSUE TITLE
[2W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by yougyung** [MJU-Coin/22-S-React#215]
## 📌 기능 구현 현황
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 완료 버튼을 누르면, 배경 색상이 변경되게 기능을 추가했어요
![image](https://user-images.githubusercontent.com/75975946/184478611-1b5f4bcf-2821-4554-805c-f6fd603f7907.png)

### 주요 개발 내용 2
- 할 일을  click하면, input창이 등장하여 새롭게 내용을 작성하는 경우, 새로 작성된 content가 저장되게 수정 기능을 추가했어요
![image](https://user-images.githubusercontent.com/75975946/184478632-5fef6702-9a21-4522-9987-a4b2be4c7206.png)

**Comment by k-kbk** [comment]
👍👍👍
