### ISSUE TITLE
[3W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by euntaek4187** [MJU-Coin/22-S-React#220]
## 📌 기능 구현 현황

- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [x] 기능 구현 : Todo 아이템 전체 목록 조회
- [x] 기능 구현 : Todo 아이템 삭제
- [x] 기능 구현 : Todo 아이템 수정
- [x] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터 --진행 중
- [ ] 화면 필터 : 생성 날짜에 따른 필터 --진행 중
- [ ] 화면 레이아웃 구현 : Grid View --진행 중

### 주요 개발 내용 1
- todo 아이템 추가 , 삭제 , 수정 , 전체목록조회? 구현했습니다
- 그리드형 구현을 고민중입니다..

### 주요 개발 내용 2
- 사진에 보이는 전체목록 개수 나타내는게 "기능 구현 : Todo 아이템 전체 목록 조회" 이거 맞나요..?
- 
![이슈제출](https://user-images.githubusercontent.com/108321588/184575146-02312b2c-23da-47e5-91e2-74bbf1366297.png)

그리고.. 
"기능 구현 : Todo 아이템 상태 변경"
이건 어떤 기능을 말하는건지 이해가 잘 안됩니다.. ㅠ

**Comment by dojinyou** [comment]
- 전체 조회 맞음!
- 아이템 상태 변경은 사람이 체크해서 변경되는 Todo의 상태(했음, 안 했음)을 통신처리!

**Comment by euntaek4187** [comment]
아하..감사합니다!
