### ISSUE TITLE
[3W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by xxxjinn** [MJU-Coin/22-S-React#221]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 음.... axios.... 이용해서.... 다시 시작하는 중입니다. 처음엔 너무 막막했었는데 대충 어찌저찌 참고하다보니 post랑 get이 어떤식인지는 이해가 갔는데 
<img width="1257" alt="화면 캡처 2022-08-16 015027" src="https://user-images.githubusercontent.com/102955516/184679332-7b8b417a-9f08-4467-9b83-d32647080818.png">

요렇게나와서... 뭘 잘못하고 있는걸까요? 화면에서 보이는 todolist에 있는 4개의 todo들은 리액트에 초기로 써 둔 것입니다.

**Comment by dojinyou** [comment]
개발자 도구에서 한번 확인 해봐야 될 거 같은데!! 연결 자체가 안되는 거는 CORS 때문일 수도...!?
