### ISSUE TITLE
[3W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by keemsebin** [MJU-Coin/22-S-React#222]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [X] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- axios 사용해서 서버랑 연결하고 있습니다 ! 코드 짰던 것들이 거의 지워지고 있어요.. axios 연결하니까 갑자기 잘되던 아이템 추가가 안돼서 수정중입니다!

**Comment by dojinyou** [comment]
원래는 개발할 때 axios로 서버 연결이 가능하다면 그쪽부터 해놓고 하는 게 좋지!
