### ISSUE TITLE
[3W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by JinseoHong0** [MJU-Coin/22-S-React#224]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 수정 & 날짜 기능 추가했습니다. 이제 필터 넣는 기능도 개발해봐야겠네요.
- ![스크린샷 2022-08-16 오후 10 43 08](https://user-images.githubusercontent.com/108217489/184895638-25cec4b6-2862-4b77-9582-8cbd3016e07c.png)

**Comment by MinsuKim21** [comment]
빠르게 해야겠네 파이팅
