### ISSUE TITLE
[3W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by yougyung** [MJU-Coin/22-S-React#226]
## 📌 기능 구현 현황
 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [X] 화면 필터 : 완료 여부에 따른 필터
- [X] 화면 필터 : 생성 날짜에 따른 필터
- [X] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 해야하는 일만 확인할 수 있는 필터 생성
![image](https://user-images.githubusercontent.com/75975946/185207534-822a27fc-a88c-4aa0-b01a-4d7dd66d86fc.png)

### 주요 개발 내용 2
- 날짜 별로 todo 확인이 가능한 필터링 기능을 생성
![image](https://user-images.githubusercontent.com/75975946/185208161-bbfea82e-537c-45ed-9aa5-76d58ef02277.png)

### 주요 개발 내용 3
- gridView 레이아웃 구현
![image](https://user-images.githubusercontent.com/75975946/185207012-4b05490e-d90f-4ecc-b78a-3e88fc0ce0f2.png)

**Comment by k-kbk** [comment]
굿굿 👍
