### ISSUE TITLE
[3W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by asylee02** [MJU-Coin/22-S-React#227]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
수정이랑 삭제도 거의 다 했고, 필터만 고민하면 될거같아요
![image](https://user-images.githubusercontent.com/87488288/185250541-a3f6313c-a836-4558-a07e-19b7f3eac0bf.png)
