### ISSUE TITLE
[3W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by xxxjinn** [MJU-Coin/22-S-React#228]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 우 와 ~~~~!!!!!!!!!!!!!~~~~~~~~~~~ 서버랑 연결하는 건 드디어 조장님 덕분에 해결했고 목록이 보입니다 !
  사실 별 거 아니었지만.. 너무 신기하고 앞으로 삭제랑 .. 등등 많이 남았지만 남은 시간 동안 열심히 해보겠습니다. 혹시나 기간 안에 다 못하더라도 따로 끝까지 해보려구요 
  개인이 만드는 거지만 혼자가 아니라 팀원들이 있어서 든든하다는 느낌을 받아서 역시 카우 붙은 게 저에게는 신의 한수..

**Comment by dojinyou** [comment]
오오오오오!! 끝까지 화이팅해서 할 수 있는 만큼 최대한 구현해보자
