### ISSUE TITLE
[3W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by euntaek4187** [MJU-Coin/22-S-React#229]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [x] 기능 구현 : Todo 아이템 전체 목록 조회
- [x] 기능 구현 : Todo 아이템 삭제
- [x] 기능 구현 : Todo 아이템 수정
- [x] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터 -- 진행 중!
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [x] 화면 레이아웃 구현 : Grid View -- 진행 중!

### 주요 개발 내용 1
조금 이상하긴 하지만,,
그리드뷰 버튼을 눌렀을때 새 레이아웃에 그리드뷰 형태를 나타내도록 구현해보았습니다...
![dltbwpcnf2](https://user-images.githubusercontent.com/108321588/185298582-04051280-8a1f-4aee-b142-36ebc5c2b399.png)
이것도 그리드뷰로 쳐주시나요? ㅠㅠㅠㅠ
### 주요 개발 내용 2
기능중 완료여부에 따른 필터를
 filter()메소드와 map()함수를 사용해서
구현중입니다.

**Comment by dojinyou** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ아니 이건 쫌... 그리드 뷰가 아니라 가로 뷰아닌가요??
필터 기능을 고차함수 좋지
