### ISSUE TITLE
[3W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by keemsebin** [MJU-Coin/22-S-React#231]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [X] 화면 필터 : 완료 여부에 따른 필터
- [X] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
-  완료여부에 따른 필터 구현중인데 생각대로 안돼서 엎었습니다.. 오기가 생겨요 

 라고 올렸었는데 방금 구현 성공했습니다!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dojinyou** [comment]
오호.... 구현 성공까쥐! 완벽해
