### ISSUE TITLE
[3W2D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by JinseoHong0** [MJU-Coin/22-S-React#232]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [X] 화면 필터 : 완료 여부에 따른 필터
- [X] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 백엔드 연결 시도는 해보지 못했지만, 기능은 대부분 구현해두긴 했습니다. css적으로는 손 볼 부분이 많지만,, 나름 많이 완성해서 만족이네요
- ![스크린샷 2022-08-19 오전 3 58 40](https://user-images.githubusercontent.com/108217489/185476286-32db266d-b8a9-466f-92ff-08781aff3d4d.png)
