### ISSUE TITLE
[3W3D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by asylee02** [MJU-Coin/22-S-React#233]
## 📌 기능 구현 현황

 
- [X] 화면 컴포넌트 구현
- [X] 화면 레이아웃 구현 : List View
- [X] 기능 구현 : Todo 아이템 추가
- [X] 기능 구현 : Todo 아이템 전체 목록 조회
- [X] 기능 구현 : Todo 아이템 삭제
- [X] 기능 구현 : Todo 아이템 수정
- [X] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터 --- 진행중
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 삭제 수정 기능까지 구현했고, 체크 표시에 따라 토글로 false true 설정해서
옆에 있는 필터 클릭시 바뀌게 하려고 했는데 잘 안되어서 아직 그 필터까지는 못했는데,
프로젝트 시간이 지나더라도 날짜랑 필터 기능 부분은 하려고합니다.
이번 프로젝트 하는데에 시간이 별로 없어서 못한 부분이 많아서 많이 아쉬웠습니다.
![image](https://user-images.githubusercontent.com/87488288/185524035-e5e40913-ba73-4ff9-ac83-cb9d72a7a2bb.png)
